name: Auto Version Update

on:
  push:
    branches:
      - main # Trigger on push to main branch

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag version
        id: get_version
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          echo "Current Version: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          TAG=${{ env.TAG }}
          VERSION=$(echo $TAG | sed 's/^v//')
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="v$MAJOR.$MINOR.$NEW_PATCH"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "New Version: $NEW_VERSION"

      - name: Set remote URL with token for push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.CUSTOM_GITHUB_PAT }}@github.com/${{ github.repository }}.git

      - name: Create and push new version tag
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.NEW_VERSION }}
          git push origin ${{ env.NEW_VERSION }}

      - name: Update version in .env file
        run: echo "APP_VERSION=${{ env.NEW_VERSION }}" > .env.version

      - name: Commit version update
        env:
          CUSTOM_GITHUB_PAT: ${{ secrets.CUSTOM_GITHUB_PAT }}
        run: |
          git add .env.version
          git commit -m "Update version to ${{ env.NEW_VERSION }}"
          git push origin main
