name: Update Version Automatically

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag version
        id: get_version
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Increment version
        id: increment_version
        run: |
          TAG=${{ steps.get_version.outputs.tag }}
          VERSION=$(echo $TAG | sed 's/^v//')
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="v$MAJOR.$MINOR.$NEW_PATCH"
          echo "::set-output name=new_version::$NEW_VERSION"

      - name: Create new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NEW_VERSION=${{ steps.increment_version.outputs.new_version }}
          git tag $NEW_VERSION
          git push origin $NEW_VERSION

      - name: Update version in .env file
        run: echo "APP_VERSION=${{ steps.increment_version.outputs.new_version }}" > .env.version

      - name: Commit updated .env.version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .env.version
          git commit -m "Update version to ${{ steps.increment_version.outputs.new_version }}"
          git push origin main
