name: Update Version Automatically

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag version
        id: get_version
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          TAG=${{ env.TAG }}
          VERSION=$(echo $TAG | sed 's/^v//')
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="v$MAJOR.$MINOR.$NEW_PATCH"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV



      - name: Create and push new tag
        run: |
          git config --global user.name "balitechsolution11061998"
          git config --global user.email "balitechsolution11061998@gmail.com"
          git tag ${{ steps.increment_version.outputs.new_version }}
          git push origin ${{ steps.increment_version.outputs.new_version }}



      - name: Update version in .env file
        run: echo "APP_VERSION=${{ env.NEW_VERSION }}" > .env.version

      - name: Commit updated .env.version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "balitechsolution11061998"
          git config --global user.email "balitechsolution11061998@gmail.com"
          git add .env.version
          git commit -m "Update version to ${{ env.NEW_VERSION }}"
          git push origin main
